# Generated by Django 4.2.7 on 2024-04-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0005_rename_is_delete_notification_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
