# Generated by Django 4.2.7 on 2024-04-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='established_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
