# Generated by Django 4.2.7 on 2024-04-11 09:12

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=16, null=True, unique=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now, null=True)),
                ('abouts_user', models.TextField(max_length=500, null=True)),
                ('photo_url', models.ImageField(max_length=500, null=True, upload_to='user_images/')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.CharField(default='Self', max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_by', models.CharField(max_length=50, null=True)),
                ('modify_date', models.DateField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_types', models.CharField(choices=[('Others', 'Others'), ('Cake', 'Cake'), ('Green vegetables', 'Green vegetables'), ('Biscuits & Chocolates', 'Biscuits & Chocolates'), ('Sweet Snack', 'Sweet Snack'), ('Stable Food', 'Stable Food'), ('Fruits', 'Fruits'), ('Meets', 'Meets'), ('Water & Cold Drinks', 'Water & Cold Drinks')], default='Others', max_length=50)),
                ('quantity', models.IntegerField(null=True)),
                ('expire_time', models.CharField(max_length=10, null=True)),
                ('pick_up_location', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=16, default=0.0, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, default=0.0, max_digits=22)),
                ('descriptions', models.TextField(null=True)),
                ('stream_url', models.ImageField(max_length=500, null=True, upload_to='food_images/')),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='New', max_length=20)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_by', models.CharField(max_length=50, null=True)),
                ('modify_date', models.DateField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=100, unique=True)),
                ('ngo_email', models.EmailField(max_length=50, unique=True)),
                ('ngo_location', models.CharField(max_length=100, null=True)),
                ('ngo_contact', models.CharField(max_length=15, unique=True)),
                ('established_date', models.DateField(verbose_name=datetime.datetime.now)),
                ('abouts_ngo', models.TextField(null=True)),
                ('ngo_stream_url', models.ImageField(null=True, upload_to='food_images/')),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_by', models.CharField(max_length=50, null=True)),
                ('modify_date', models.DateField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_to', models.CharField(choices=[('donor', 'Complaint to Donor'), ('volunteer', 'Complaint to Volunteer'), ('farmer', 'Complaint to Farmer')], max_length=30, null=True)),
                ('descriptions', models.TextField(null=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_by', models.CharField(max_length=50, null=True)),
                ('modify_date', models.DateField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodshare.food')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('report_description', models.TextField()),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(max_length=300, null=True)),
                ('distributed_location', models.CharField(max_length=100, null=True)),
                ('rating_point', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('distributed_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modify_by', models.CharField(max_length=50, null=True)),
                ('modify_date', models.DateField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodshare.food')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
