# Generated by Django 4.2.7 on 2024-04-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='report_description',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
