# Generated by Django 4.2.7 on 2024-04-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare', '0003_alter_users_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ngo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodshare.ngo'),
        ),
    ]
